### ISSUE TITLE
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by berlinhudson** [driftyco/ionic-plugins-deploy#19]
Hi guys,

when I compile with the plugin version 0.2.1 for my Nexus 7 with Android 5.1 all is working well.
When I compile for older Samsung with Android 4.2.2 the app crashes and I get that message:

E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-2
    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
            at com.ionic.deploy.IonicDeploy.postDeviceDetails(IonicDeploy.java:387)
            at com.ionic.deploy.IonicDeploy.checkForUpdates(IonicDeploy.java:217)
            at com.ionic.deploy.IonicDeploy.access$000(IonicDeploy.java:49)
            at com.ionic.deploy.IonicDeploy$1.run(IonicDeploy.java:171)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

I'm using:
Crosswalk 12.41.296.5.
Java version is 1.7
Target SDK is 22
Min SDK is 15

Probably has something to do that https://developer.android.com/reference/java/nio/charset/StandardCharsets.html has been added at API 19. But still that souldn't be a problem since my target is 22, right?

**Comment by PaperMonster** [comment]
It is obviously a problem since your min SDK is 15 while the plugin uses a class from API 19. My temporary fix is changing line 387 in IonicDeploy.java to `byte[] postData = params.getBytes("UTF-8" );` which avoid using such class.
